import { adminDb } from '../config/firebaseAdmin.js';
import { persistentStorage } from './storage.js';
import type { AppLimitsConfig, AppSettingsConfig, SystemPromptConfig } from '../../types.js';
const hasServiceAccount = Boolean(process.env.FIREBASE_PRIVATE_KEY && process.env.FIREBASE_CLIENT_EMAIL);
const CONFIG_CACHE_TTL_MS=3000;
let systemCache:{value:SystemPromptConfig;expires:number}|null=null;
let limitsCache:{value:AppLimitsConfig;expires:number}|null=null;
let settingsCache:{value:AppSettingsConfig;expires:number}|null=null;
const DEFAULT_SYSTEM_PROMPT=process.env.DEFAULT_SYSTEM_PROMPT||'You are AbyssGPT, a capable, direct, analytical conversational AI assistant. Speak clearly and helpfully.';
const DEFAULT_LIMITS:AppLimitsConfig={free:{dailyMessageLimit:20,rateLimitPerMinute:5,contextLimit:10},premium:{dailyMessageLimit:200,rateLimitPerMinute:30,contextLimit:30}};
const DEFAULT_SETTINGS:AppSettingsConfig={appName:'AbyssGPT',welcomeMessage:'Welcome to AbyssGPT. Ask anything and get a direct, thoughtful response.',maintenanceMode:false,registrationEnabled:true,maxMessageLength:4000,premiumPriceInr:Number(process.env.PREMIUM_PRICE_INR)||299,telegramUsername:process.env.TELEGRAM_USERNAME||'@MrNewton_2',premiumBenefits:['200 Daily Messages','30 Requests / minute','30 Message Context Window','Priority reasoning experience','Unlimited conversation history'],defaultPremiumDurationDays:30};
async function remote(doc:string){ if(!hasServiceAccount)return null; const s=await adminDb.collection('appConfig').doc(doc).get(); return s.exists?s.data():null; }
export async function getSystemPromptConfig(){ const now=Date.now(); if(systemCache&&systemCache.expires>now)return systemCache.value; const remoteData=await remote('system'); if(remoteData?.systemPrompt){const v=remoteData as SystemPromptConfig; persistentStorage.saveSystemPromptConfig(v); systemCache={value:v,expires:now+CONFIG_CACHE_TTL_MS}; return v;} const local=persistentStorage.getSystemPromptConfig(); if(local?.systemPrompt){systemCache={value:local,expires:now+CONFIG_CACHE_TTL_MS}; return local;} const v={systemPrompt:DEFAULT_SYSTEM_PROMPT,previousPrompts:[],updatedAt:new Date().toISOString(),updatedBy:'system'}; persistentStorage.saveSystemPromptConfig(v); if(hasServiceAccount)await adminDb.collection('appConfig').doc('system').set(v,{merge:true}); systemCache={value:v,expires:now+CONFIG_CACHE_TTL_MS}; return v; }
export async function updateSystemPrompt(newPrompt:string,updatedBy:string){ if(!newPrompt.trim())throw new Error('System prompt cannot be empty.'); const current=await getSystemPromptConfig(); const v={systemPrompt:newPrompt.trim(),previousPrompts:[...(current.previousPrompts||[]),...(current.systemPrompt&&current.systemPrompt!==newPrompt?[{prompt:current.systemPrompt,updatedAt:current.updatedAt,updatedBy:current.updatedBy}]:[])].slice(-10),updatedAt:new Date().toISOString(),updatedBy}; persistentStorage.saveSystemPromptConfig(v); systemCache={value:v,expires:Date.now()+CONFIG_CACHE_TTL_MS}; if(hasServiceAccount)await adminDb.collection('appConfig').doc('system').set(v,{merge:true}); return v; }
export async function getAppLimitsConfig(){ const now=Date.now(); if(limitsCache&&limitsCache.expires>now)return limitsCache.value; const remoteData=await remote('limits'); const source=(remoteData||persistentStorage.getAppLimitsConfig()||{}) as Partial<AppLimitsConfig>; const v={free:{...DEFAULT_LIMITS.free,...(source.free||{})},premium:{...DEFAULT_LIMITS.premium,...(source.premium||{})}} as AppLimitsConfig; persistentStorage.saveAppLimitsConfig(v); limitsCache={value:v,expires:now+CONFIG_CACHE_TTL_MS}; return v; }
export async function updateAppLimitsConfig(newLimits:Partial<AppLimitsConfig>,updatedBy:string){ const c=await getAppLimitsConfig(); const v={free:{...c.free,...(newLimits.free||{})},premium:{...c.premium,...(newLimits.premium||{})},updatedAt:new Date().toISOString(),updatedBy}; persistentStorage.saveAppLimitsConfig(v); limitsCache={value:v,expires:Date.now()+CONFIG_CACHE_TTL_MS}; if(hasServiceAccount)await adminDb.collection('appConfig').doc('limits').set(v,{merge:true}); return v; }
export async function getAppSettingsConfig(){ const now=Date.now(); if(settingsCache&&settingsCache.expires>now)return settingsCache.value; const remoteData=await remote('settings'); const v={...DEFAULT_SETTINGS,...(remoteData||persistentStorage.getAppSettingsConfig()||{})} as AppSettingsConfig; persistentStorage.saveAppSettingsConfig(v); settingsCache={value:v,expires:now+CONFIG_CACHE_TTL_MS}; return v; }
export async function updateAppSettingsConfig(newSettings:Partial<AppSettingsConfig>,updatedBy:string){ const c=await getAppSettingsConfig(); const v={...c,...newSettings,updatedAt:new Date().toISOString(),updatedBy}; persistentStorage.saveAppSettingsConfig(v); settingsCache={value:v,expires:Date.now()+CONFIG_CACHE_TTL_MS}; if(hasServiceAccount)await adminDb.collection('appConfig').doc('settings').set(v,{merge:true}); return v; }
